name: Cypress e2e tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

  cypress-run:
    runs-on: ubuntu-latest
    needs: ['install']
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2, 3, 4 ]

    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          build: npm run generate
          start: npm start
          wait-on: http://localhost:3000
          browser: chrome
          record: true
          parallel: true
          group: 'e2e tests'

  deploy:
    runs-on: ubuntu-latest
    needs: ['install', 'cypress-run']
    steps:
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
